# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lucas/Github/chip8-emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lucas/Github/chip8-emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Github/chip8-emulator/CMakeFiles /home/lucas/Github/chip8-emulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lucas/Github/chip8-emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named chip8_emulator

# Build rule for target.
chip8_emulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 chip8_emulator
.PHONY : chip8_emulator

# fast build rule for target.
chip8_emulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/build
.PHONY : chip8_emulator/fast

src/chip8_emulator.o: src/chip8_emulator.cpp.o

.PHONY : src/chip8_emulator.o

# target to build an object file
src/chip8_emulator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/chip8_emulator.cpp.o
.PHONY : src/chip8_emulator.cpp.o

src/chip8_emulator.i: src/chip8_emulator.cpp.i

.PHONY : src/chip8_emulator.i

# target to preprocess a source file
src/chip8_emulator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/chip8_emulator.cpp.i
.PHONY : src/chip8_emulator.cpp.i

src/chip8_emulator.s: src/chip8_emulator.cpp.s

.PHONY : src/chip8_emulator.s

# target to generate assembly for a file
src/chip8_emulator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/chip8_emulator.cpp.s
.PHONY : src/chip8_emulator.cpp.s

src/cpu.o: src/cpu.cpp.o

.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i

.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s

.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o

.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i

.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s

.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

src/video.o: src/video.cpp.o

.PHONY : src/video.o

# target to build an object file
src/video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/video.cpp.o
.PHONY : src/video.cpp.o

src/video.i: src/video.cpp.i

.PHONY : src/video.i

# target to preprocess a source file
src/video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/video.cpp.i
.PHONY : src/video.cpp.i

src/video.s: src/video.cpp.s

.PHONY : src/video.s

# target to generate assembly for a file
src/video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/chip8_emulator.dir/build.make CMakeFiles/chip8_emulator.dir/src/video.cpp.s
.PHONY : src/video.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... chip8_emulator"
	@echo "... src/chip8_emulator.o"
	@echo "... src/chip8_emulator.i"
	@echo "... src/chip8_emulator.s"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... src/video.o"
	@echo "... src/video.i"
	@echo "... src/video.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

